[tool.poetry]
name = "chispa"
version = "0.10.0"
description = "Pyspark test helper library"
authors = ["MrPowers <matthewkevinpowers@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.2"
pyspark = ">3.0.0"
findspark = "1.4.2"
pytest-describe = "^2.1.0"

[tool.poetry.group.mkdocs.dependencies]
mkdocs = "^1.6.0"
mkdocstrings-python = "*"
mkdocs-gen-files = "*"
mkdocs-literate-nav = "*"
mkdocs-section-index = "*"
markdown-include = "*"
mkdocs-material = "*"

[tool.poetry.group.mkdocs]
optional = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
